### PR TITLE
docs(samples): Snippet for submitting jobs to cluster pools using templates

### PR DESCRIPTION
**Pull request by datasherlock**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-dataproc/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Review by parthea — CHANGES_REQUESTED** [review]
Please could you add a `*_test.py` file also, similar to [this one](https://github.com/googleapis/python-dataproc/blob/main/samples/snippets/submit_job_test.py#L74)?

**Comment by meredithslota** [comment]
Please also update the region tag to include the product prefix.

**Comment by datasherlock** [comment]
I have added a pytest file and also modified the region tags to include the prefixes

**Comment by dandhlee** [comment]
Hey @datasherlock, we're consolidating handwritten samples to https://github.com/GoogleCloudPlatform/python-docs-samples. Could you open this PR on python-docs-samples instead? I can help take a look at the PR.

**Pull request closed without merging**
