### PR TITLE
chore: add SPOT to enum of preemptibility

### LINKED ISSUE #506: Allow creating dataproc secondary workers as spot instances.
**Is your feature request related to a problem? Please describe.**
As GCP introduced a new generation of preemptible instances which is called [Spot instance](https://cloud.google.com/compute/docs/instances/spot). 
I'm trying to create a dataproc cluster with secondary workers as spot instances. But seems like in this [line 778](https://github.com/googleapis/python-dataproc/blob/main/google/cloud/dataproc_v1/types/clusters.py#L778). There is no option to fulfill the request as gcloud cli does.

``` bash
gcloud dataproc clusters create dummy \
 --region us-central1 \
 --zone us-central1-b \
...
 --num-workers 2 \
 --num-secondary-workers 0 \
 --secondary-worker-type=**spot** \
 --master-machine-type n1-standard-2 \
 --worker-machine-type n1-standard-4
...
```

 **Describe the solution you'd like**
I think we can declare a new value to the `Preemptibility` enum which is SPOT and support parsing it to API body before making request.

### PR DESCRIPTION
**Pull request by tqtensor**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-dataproc/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #506 🦕

Here is a simple test to create Dataproc cluster with SPOT instance. [Colab](https://colab.research.google.com/drive/1FE4vIg2P00RzuRVPpXD1-6yEKEAbHWzt?usp=sharing)

### CODE REVIEW

**Comment by sudohainguyen** [comment]
+1

**Comment by binhflow** [comment]
+1

**Comment by tqtensor** [comment]
Dear @parthea and @msampathkumar,

I am sorry to bother you all, but I don't know anyone to contact about this issue. This PR is pretty simple; I want to add the SPOT instance type to the enum of preemptibility to allow the Dataproc client to create a cluster with SPOT machines.

Who else should I contact to review this PR? If you know them, please tag them here.

Thank you.

**Comment by parthea** [comment]
Googlers see cl/499867716 with proposal to update https://github.com/googleapis/googleapis/tree/master/google/cloud/dataproc/v1

**Pull request closed without merging**
